#Sabiendo que ValueError es la excepción que se lanza cuando no podemos convertir una cadena de texto en su valor numérico, escriba una función get_int() que lea un valor entero del usuario y lo devuelva, iterando mientras el valor no sea correcto. Intente resolver el ejercicio tanto de manera iterativa como recursiva

def get_int_recursivo():
    try:
        valor = int(input("Ingrese un valor entero: "))
        return valor
    except ValueError:
        print("Error: El valor ingresado no es válido. Intente nuevamente.")
        return get_int_recursivo()
entero = get_int_recursivo()
print(f"Usted ha ingresado el valor entero: {entero}")